### ISSUE TITLE
Removing unroundings.css and using panel-roundness > 0px

### ISSUE THREAD

**Issue by trsted** [refact0r/system24#42]
Hey again,

when removing the unrounding.css and thus using --panel-roundness some corners/edges start disappearing with increased px size.
Using a higher value makes it more noticable.
I really like the look of the rounded panels but the edges are pretty distracting.

If you find a fix that would be awesome!
--panel-roundness: 0px
![image](https://github.com/user-attachments/assets/e15b0376-d188-48a3-bfa5-c9d7854eabae)

--panel-roundness: 30px
![image](https://github.com/user-attachments/assets/3f2c7984-4f5d-4ebe-84f6-98b90c05fcbc)

![image](https://github.com/user-attachments/assets/89791937-a496-4bf8-8890-dc8eea137e3f)

Show User Profile looks fine, but funnily again the Message panel has no edges on the right side.
![image](https://github.com/user-attachments/assets/50d7e073-2be8-429b-9660-ffb66e8c8733)

Bonus: Because I don't want to open a third issue (i am already so sorry), the embedded profile in the profile side panel is not getting rounded.
![image](https://github.com/user-attachments/assets/555366af-f5ba-4104-a834-0d78fa0dd63e)

Otherwise thanks again! And I love this theme, the reason why I submit the issues so it can get even better. <3

**Comment by Androser420** [comment]
hey there, I just made a little workaround for this that I'm currently using, it's not perfect *but* it should get the job done
put this in your .theme.css:
```css
/* lazy rounding fix for Apps section */
[class^="channelAppLauncher_"]>[class^="buttonContainer_"] {
    &>[class^="button_"] {
        transform: scale(0.5);
    }

    & [class^="contents"]>[class^="lottieIcon_"] {
        transform: scale(2);
    }
}

/* server discovery */
ul {
    [class^='footer'] {
        background: transparent
    }

    [class^='gradient'] {
        background: var(--bg-overlay-app-frame, var(--background-tertiary))
    }
}

/* user profile */
[class^='userPanelInner_'] {
    border-radius: var(--panel-roundness);
}

/* server banner */
[class^='animatedContainer_'] {
    border-top-left-radius: calc(var(--panel-roundness) /1.5);
    border-top-right-radius: calc(var(--panel-roundness) /1.5);
}
```
let me know if it works for you!

**Comment by trsted** [comment]
the hidden corners/edges are definitely fixed with that, perfect.
user profiles also look better, but still a bit off. but this works for now, thanks!
![image](https://github.com/user-attachments/assets/bd99a093-932d-4add-975a-c0c7b2e64ab8)

I will leave the issue open for a while if you think the user profile roundness can still be improved. I think if the red part that is now seen on the edges would be removed, the rounding would look better

**Comment by Androser420** [comment]
hmm im not really sure i can completely get rid it but u could probably change the border radius to something like:
```css
border-radius: calc(var(--panel-roundness) - var(--txt-pad) - 2px);
```
this isnt reliable but atleast its mostly covered by the banner now

**Comment by trsted** [comment]
25px
![image](https://github.com/user-attachments/assets/9a51820c-1b36-4f87-8e81-fbae2466b9c3)
This is with `--panel-roundness: 25px` Nice, this seems to work better now! :)

I don't want to be annoying, but with `--panel-roundness: 15px` the effect is barely visible, and the corners look sharp. 15px is my preferred value here. I tried adjusting the formula myself a bit, but I don't fully understand how it works. If it could look more like the 25px setting here, I would be super satisfied! <3
15px
![image](https://github.com/user-attachments/assets/4271dc0b-0dfc-4283-86f3-1b9c0efb52b5)

**Comment by Androser420** [comment]
hey, im so sorry for making you wait this long
i dont think its very doable except maybe making the outer padding smaller

```css
/* user profile */
[class^='userPanelInner_'] {
    border-radius: calc(var(--panel-roundness) - var(--txt-pad) - 2px);
}

[class^='userPanelOuter_'] {
    padding: 3px;
    --txt-pad: 3px;
}
```

![image](https://github.com/user-attachments/assets/b7fd3054-9d19-47f3-87c2-4bbcf0877772)

this is all i can think of for now, hopefully someone looks over this and comes up with a proper solution, cheers!
