### ISSUE TITLE
Overflow broken

### ISSUE THREAD

**Issue by pwall2222** [refact0r/system24#48]
I am using Legcord + Vencord (using Vencord to load the theme), and the overflows for people status is broken. I did a quick bodge (doesn't work 100% of the time) with:

```css
[class^=peopleColumn_] {
    overflow-x: hidden !important;
}
```

(adding `.container_c2739c` to that selector would solve the issue but make the `channel` text cut out)

![image](https://github.com/user-attachments/assets/4c4ee462-9a9f-4c34-964c-3179711696e9)

**Comment by Androser420** [comment]
the reason text gets cut off is because keeping the overflow for the container visible actually fixes that
https://github.com/refact0r/system24/blob/040e05fe3029ab7a5c68f2f71671aa7a0767df57/src/main.css#L402
so to actually make that "work" you could probably do something like this:
```css
.container_c2739c {
    padding-top: 10px;
    margin-top: -10px;
}
```
basically u add some padding to the top and move the whole thing up aswell with the same amount of pixels to give it some space to render

**Comment by Androser420** [comment]
oh btw I also noticed the names get a lot shorter too so u could fix that up if necessary
```css
.discriminator_f3939d {
    display: none;
}

.hovered_f3939d .discriminator_f3939d {
    display: flex;
}
```

![thej](https://github.com/user-attachments/assets/5af2d5b7-2e2e-429d-be83-574aebf63784)
