### ISSUE TITLE
Text in the message box is misaligned

### ISSUE THREAD

**Issue by xzi** [refact0r/system24#51]
Text in the message box isn't properly center aligned anymore for some reason. 
![image](https://github.com/user-attachments/assets/a00ea866-bfe3-4ddc-bf04-52be6944e7d5)

This is also present in the "Message #channel-name" text
![image](https://github.com/user-attachments/assets/c044470c-c7dc-40a5-8973-6c92d2acd0fe)

**Comment by Androser420** [comment]
put this in your css
```css
[class^='textArea_'] [class*='fontSize16Padding_'] {
    padding-bottom: 16px !important;
    padding-top: 16px !important;
}
```
