### ISSUE TITLE
"Commands" button issue

### ISSUE THREAD

**Issue by M0chaCat** [refact0r/system24#63]
![CleanShot 2024-12-22 at 10 20 45](https://github.com/user-attachments/assets/72966edb-0ca7-48a8-80ba-373cbe1c6106)
discord added this dum button for bots and its kinda funky for the theme as seen above, heres what un-themed is like 
![CleanShot 2024-12-22 at 10 22 06](https://github.com/user-attachments/assets/3b0f400f-7d63-4f78-a5f1-6b45cfd5c762)

the button is in DMs with bots, carl-bot is these screenshots

**Comment by Androser420** [comment]
here, this might help
```css
[class^='entryPointButtonContainer_'] {
  align-content: center;
  border-left: var(--border-width) solid var(--border-color);
  margin: 0;

  >[class^='entryPointAppCommandButton_'] {
    margin: 6px;
  }
}
```
add it to your QuickCSS
