### ISSUE TITLE
Support for Horizontal Server List please!

### ISSUE THREAD

**Issue by C4uTi0N** [refact0r/system24#64]
As someone who uses Disocrd on my vertical second monitor, it woud be awesome if you could add "proper" support for the Horizontal Server List theme, since it gives much more space everything else.

![image](https://github.com/user-attachments/assets/4fb213b6-24d9-43f1-b04e-f211321203d9)

I'm still gonna use this theme regardless, just thought i'd be a nice to have

**Comment by Androser420** [comment]
try this out
```css
#app-mount {
    [class*='guilds_'] {
        padding-top: unset;
        max-height: calc(100vw - 2.25 * var(--pad));

        &:after {
            right: 6px;
            transform-origin: bottom right;
            transform: rotate(90deg);
            top: 28px;
            place-self: end;
        }

        [class^='footer_'] {
            padding-bottom: var(--server-spacing);
        }
    }

    [class^='app_'] [class^='base_'] {
        top: calc(var(--server-container) + var(--pad)) !important;
        margin: var(--pad);
    }
}
```
had to get a bit specific for the height but should be fine, just dont increase `--pad` too much since its not 100% accurate
also if you want more chat space, i made a theme based on this one that collapses some panels like the sidebar and member list (https://github.com/Androser420/sysmol24)
![image](https://github.com/user-attachments/assets/24d4e859-7ea3-47e7-8a7d-3537ffd72595)
enjoy!
