### ISSUE TITLE
Spacing Issue with Better Folders

### ISSUE THREAD

**Issue by Zachattack525** [refact0r/system24#65]
I use the plugin Better Folders on Vencord but it results in there being a really big gap between the main server list and sidebar, and no gap between the sidebar and server section. Any idea what I can do to fix this?

![Image](https://github.com/user-attachments/assets/c40f8348-4e9a-4ed9-8ffa-9f3b3a7028d0)

**Comment by Androser420** [comment]
here u go
```css
[style*=display]>.guilds_a4d4d9 {
  margin: var(--pad) 0;
}
```
