### ISSUE TITLE
Volume text is unreadable

### ISSUE THREAD

**Issue by C4uTi0N** [refact0r/system24#66]
When adjusting peoples volume in the right-click menu, the %-text is unreadable

![Image](https://github.com/user-attachments/assets/af4292b8-18cc-4a60-b83a-108befb9f1e5)

**Comment by Androser420** [comment]
```css
[class*='tooltipGrey_'] {
  background-color: var(--bg-2);
  color: var(--txt-1);
}
```
![Image](https://github.com/user-attachments/assets/9dd7bd5f-1b63-40e1-bf1e-ebc5301a3454)
or if you wanna match other tooltips, change background color to `--bg-0`
![Image](https://github.com/user-attachments/assets/a39d0ed5-32ce-46cd-8049-2dcb5182a326)
and if you wanna change all tooltips, and not just that one, change the class name to
```css
[class^='tooltip_']
```
