### ISSUE TITLE
Horizontal Ruler Transparency

### ISSUE THREAD

**Issue by permafrozen** [refact0r/system24#99]
Hello, is it possible to make the horizontal rulers across the pages transparent? I really don't like how there are strokes of solid color through the pages.

Here is what I mean, you may need to zoom in to spot it:

![Image](https://github.com/user-attachments/assets/871df9f9-b78a-452c-bc8b-3503ee9b7d75)

**Comment by rumpff** [comment]
add this to your QuickCSS to hide them

```css
div[class^=peopleListItem] {
    border: none;
}
```
